// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq2c8nky1UREau-scxCMCLloI_gWuvyc0',
    appId: '1:968907424518:web:d123dfd5c6a4cebe1a9487',
    messagingSenderId: '968907424518',
    projectId: 'storeapp-6db64',
    authDomain: 'storeapp-6db64.firebaseapp.com',
    storageBucket: 'storeapp-6db64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdBZzPhSLxyE4T0VxsM2O3iF1egOWMXs',
    appId: '1:968907424518:android:e59198df03aa799b1a9487',
    messagingSenderId: '968907424518',
    projectId: 'storeapp-6db64',
    storageBucket: 'storeapp-6db64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEyqOSrFPLcUiNxS7Ri1zNfRQRnUwm4w',
    appId: '1:968907424518:ios:d87d75ae1ca0b5b11a9487',
    messagingSenderId: '968907424518',
    projectId: 'storeapp-6db64',
    storageBucket: 'storeapp-6db64.firebasestorage.app',
    iosBundleId: 'com.example.electricalStoreMobileAppSqllite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEyqOSrFPLcUiNxS7Ri1zNfRQRnUwm4w',
    appId: '1:968907424518:ios:d87d75ae1ca0b5b11a9487',
    messagingSenderId: '968907424518',
    projectId: 'storeapp-6db64',
    storageBucket: 'storeapp-6db64.firebasestorage.app',
    iosBundleId: 'com.example.electricalStoreMobileAppSqllite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq2c8nky1UREau-scxCMCLloI_gWuvyc0',
    appId: '1:968907424518:web:cbc39dce09353be91a9487',
    messagingSenderId: '968907424518',
    projectId: 'storeapp-6db64',
    authDomain: 'storeapp-6db64.firebaseapp.com',
    storageBucket: 'storeapp-6db64.firebasestorage.app',
  );
}
